//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TriviadorTheGame.Models.DataBaseModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TriviadorTheGameDBEntities1 : DbContext
    {
        public TriviadorTheGameDBEntities1()
            : base("name=TriviadorTheGameDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Question> Questions { get; set; }
        public virtual DbSet<QuestionsPack> QuestionsPacks { get; set; }
        public virtual DbSet<QuestionsToPack> QuestionsToPacks { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserStatistic> UserStatistics { get; set; }
    }
}
