//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TriviadorTheGame.Models.DataBaseModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionsToPack
    {
        public int QUESTION_TO_PACK_ID { get; set; }
        public Nullable<int> QUESTION_ID { get; set; }
        public Nullable<int> QUESTION_PACK_ID { get; set; }
    
        public virtual Question Question { get; set; }
        public virtual QuestionsPack QuestionsPack { get; set; }
    }
}
